name: Ugolek
options:
  bundleIdPrefix: com.ugolek
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1"
targets:
  Ugolek:
    type: application
    platform: iOS
    sources:
      - path: Ugolek
    info:
      path: Ugolek/Info.plist
      properties:
        CFBundleDisplayName: Уголёк
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        ITSAppUsesNonExemptEncryption: false
