version: "3.8"

services:
  signer:
    build: .
    container_name: ugolek-signer
    volumes:
      - ./work:/work
    devices:
      - /dev/bus/usb:/dev/bus/usb
    privileged: true
    network_mode: host
    environment:
      - DOCKER=1
